language: go
go:
  - 1.4
  - tip

install:
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/jordwest/mock-conn
  - go get badc0de.net/pkg/dummycertbuilder